Update Swift Versions
vapor/toolbox pull request #456
Opened 2024-04-17 14:23 UTC by 0xTim

Bumps the integration tests to 5.10 to match the template and the toolbox minimum Swift version to 5.8 to match Vapor

2024-05-10 09:56 UTC, gwynne commented
We want to keep the toolbox compatible with 5.5 for users on old versions of macOS. I recently had to do a PR to _restore_ that compatibility. There's no need to bump that minimum (though bumping the integration tests is a good idea).

2024-05-10 10:01 UTC, gwynne requested changes
See comment

2024-05-13 12:25 UTC, 0xTim commented on Package.swift
> +// swift-tools-version:5.8
```suggestion
// swift-tools-version:5.5
```

2024-05-13 12:25 UTC, 0xTim commented
Done, no need for a release then

2024-05-13 13:41 UTC, gwynne commented
@0xTim Fixing the CI requires adding the same "we now need an available database server for the template's tests" logic to the toolbox CI that I added to the template's CI (see https://github.com/vapor/template/blob/main/.github/workflows/test-template.yml#L51-L118)

2024-05-13 14:02 UTC, 0xTim commented
How the hell has this ever passed in the past

2024-05-13 14:09 UTC, gwynne commented
Those tests didn't previously exist so there was nothing to fail.

2024-05-13 14:14 UTC, 0xTim commented
Ohh right, we ran tests but didn't do anything in them. Makes sense

2024-05-13 14:45 UTC, gwynne approved these changes

2024-05-13 14:59 UTC, merged